version: "3.4"

services:
  java:
    image: vkainth/demoapp
    ports:
     - "8080:8080"
    depends_on:
     - db
    environment:
      spring.profiles.active: docker
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
     - db-data:/data/db

volumes:
  db-data:
    external:
      name: db-data
  